services:
  db:
    image: postgres:latest
    container_name: mcms_db
    environment:
      POSTGRES_DB: mcms_db
      POSTGRES_USER: mcms
      POSTGRES_PASSWORD: mcms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: